import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Book Bounty</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/landingpage.png" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.landingPageContainerOne}>

         <div className={styles.headerTextContainer}>
          <div className={styles.welcome}> <p>Welcome to</p></div>
          <div className={styles.headerText}> <p>Book Bounty</p></div>
          
         </div>

      {/*     <div className={styles.imgCtaContent}></div>
          <div className={styles.footerTextContent}> </div> */}
        </div>
      </main>
    </>
  );
}
